const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
/**
 * Report Service - generates PDF and Excel attendance reports
 */

/**
 * Generate a PDF attendance report for a session or subject
 * @param {object} data - session, records, subject info
 * @returns {Buffer} PDF buffer
 */
const generatePDFReport = (data) => {
  return new Promise((resolve, reject) => {
    const { subject, sessionDate, records, presentCount, totalStudents, faculty } = data;

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // ─── Header ────────────────────────────────────────────────────────────────
    doc.fontSize(22).font('Helvetica-Bold').fillColor('#1f428f')
      .text('AttendX', 50, 50);
    doc.fontSize(11).font('Helvetica').fillColor('#666')
      .text('Smart Wireless Attendance System', 50, 78);

    doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e0e0e0').stroke();

    // ─── Report Title ──────────────────────────────────────────────────────────
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#131313')
      .text('Attendance Report', 50, 120);
    doc.fontSize(11).font('Helvetica').fillColor('#444')
      .text(`Subject: ${subject.name} (${subject.subjectCode})`, 50, 145)
      .text(`Faculty: ${faculty}`, 50, 162)
      .text(`Date: ${new Date(sessionDate).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, 50, 179)
      .text(`Present: ${presentCount} / ${totalStudents}`, 50, 196)
      .text(`Attendance Rate: ${totalStudents > 0 ? ((presentCount / totalStudents) * 100).toFixed(1) : 0}%`, 50, 213);

    // ─── Table Header ──────────────────────────────────────────────────────────
    let y = 250;
    doc.rect(50, y, 495, 25).fillColor('#1f428f').fill();
    doc.fontSize(10).font('Helvetica-Bold').fillColor('white')
      .text('No.', 58, y + 8)
      .text('Student Name', 85, y + 8)
      .text('Status', 350, y + 8)
      .text('Marked At', 420, y + 8);

    y += 30;
    doc.fillColor('#131313');

    // ─── Table Rows ────────────────────────────────────────────────────────────
    records.forEach((rec, idx) => {
      const bg = idx % 2 === 0 ? '#f9f9f9' : '#ffffff';
      doc.rect(50, y - 4, 495, 22).fillColor(bg).fill();

      const statusColor = rec.status === 'present' ? '#2e7d32' : '#c62828';
      doc.fontSize(9.5).font('Helvetica').fillColor('#222')
        .text(idx + 1, 58, y)
        .text(rec.studentName || 'N/A', 85, y)
        .fillColor(statusColor)
        .text(rec.status.toUpperCase(), 350, y)
        .fillColor('#222')
        .text(rec.markedAt ? new Date(rec.markedAt).toLocaleTimeString('en-IN') : '—', 420, y);

      y += 22;
      if (y > 720) { doc.addPage(); y = 80; }
    });

    // ─── Footer ────────────────────────────────────────────────────────────────
    doc.fontSize(8).fillColor('#999')
      .text(`Generated by AttendX on ${new Date().toLocaleString('en-IN')}`, 50, 770, { align: 'center' });

    doc.end();
  });
};

/**
 * Generate an Excel attendance report
 * @param {object} data - report data
 * @returns {Buffer} Excel buffer
 */
const generateExcelReport = async (data) => {
  const { subject, sessionDate, records, presentCount, totalStudents, faculty } = data;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'AttendX';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Attendance', {
    pageSetup: { paperSize: 9, orientation: 'portrait' },
  });

  // Column widths
  sheet.columns = [
    { header: 'No.', key: 'no', width: 6 },
    { header: 'Student Name', key: 'name', width: 30 },
    { header: 'Email', key: 'email', width: 35 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'BLE RSSI', key: 'rssi', width: 12 },
    { header: 'Marked At', key: 'markedAt', width: 22 },
  ];

  // Header info rows
  sheet.mergeCells('A1:F1');
  sheet.getCell('A1').value = 'BEACONATTEND – ATTENDANCE REPORT';
  sheet.getCell('A1').font = { bold: true, size: 14, color: { argb: 'FF1f428f' } };
  sheet.getCell('A1').alignment = { horizontal: 'center' };

  sheet.mergeCells('A2:F2');
  sheet.getCell('A2').value = `Subject: ${subject.name} (${subject.subjectCode}) | Faculty: ${faculty} | Date: ${new Date(sessionDate).toLocaleDateString('en-IN')}`;
  sheet.getCell('A2').font = { size: 10, color: { argb: 'FF444444' } };

  sheet.mergeCells('A3:F3');
  sheet.getCell('A3').value = `Present: ${presentCount} / ${totalStudents} (${totalStudents > 0 ? ((presentCount / totalStudents) * 100).toFixed(1) : 0}%)`;
  sheet.getCell('A3').font = { size: 10, bold: true };

  sheet.addRow([]); // spacer

  // Table header row
  const headerRow = sheet.addRow(['No.', 'Student Name', 'Email', 'Status', 'BLE RSSI (dBm)', 'Marked At']);
  headerRow.eachCell((cell) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1f428f' } };
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.alignment = { horizontal: 'center' };
  });

  // Data rows
  records.forEach((rec, idx) => {
    const row = sheet.addRow([
      idx + 1,
      rec.studentName || 'N/A',
      rec.studentEmail || 'N/A',
      rec.status?.toUpperCase() || 'PRESENT',
      rec.bleRSSI ?? 'N/A',
      rec.markedAt ? new Date(rec.markedAt).toLocaleString('en-IN') : '—',
    ]);

    const statusCell = row.getCell(4);
    statusCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: rec.status === 'present' ? 'FFe8f5e9' : 'FFffebee' },
    };
    statusCell.font = { color: { argb: rec.status === 'present' ? 'FF2e7d32' : 'FFc62828' }, bold: true };

    if (idx % 2 === 0) {
      row.eachCell((cell, colNum) => {
        if (colNum !== 4) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFf5f5f5' } };
        }
      });
    }
  });

  return await workbook.xlsx.writeBuffer();
};

module.exports = { generatePDFReport, generateExcelReport };
